CREATE TABLE payment_process_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id VARCHAR2(100),
    error_message VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE OR REPLACE PROCEDURE process_pending_payments AS
BEGIN

    FOR payment_record IN (
        SELECT id
        FROM payments
        WHERE status = 'PENDING'
    )
    LOOP

        BEGIN

            UPDATE payments
            SET status = 'PROCESSED'
            WHERE id = payment_record.id
              AND status = 'PENDING';

        EXCEPTION
            WHEN OTHERS THEN

                INSERT INTO payment_process_log (
                    payment_id,
                    error_message,
                    created_at
                )
                VALUES (
                    payment_record.id,
                    SQLERRM,
                    SYSTIMESTAMP
                );

        END;

    END LOOP;

    COMMIT;

END process_pending_payments;
/